obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[0.275, 0.25], [-0.275, 0.25], [-0.275, -0.25], [0.275, -0.25]]
footprint_padding: 0.1
#robot_radius: ir_of_robot
# inflation_radius: 0.5

map_type: costmap
observation_sources: scan
scan: {sensor_frame: d400_link, data_type: LaserScan, topic: scan, marking: true, clearing: true}